// Extracts the exact vector outline of "Chorus" in Ms Madi at the same
// metrics the app renders (210px, 0.01em letter-spacing) and writes a
// React SVG component. Run with: bun scripts/extract-outline.mjs
import opentype from 'opentype.js'
import { writeFileSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))

const TEXT = 'Chorus'
const FONT_SIZE = 210
const LETTER_SPACING = 0.01 * FONT_SIZE // 0.01em -> 2.1px
const PAD = 12 // breathing room so the stroke is never clipped

const buf = readFileSync(join(__dirname, 'MsMadi-Regular.ttf'))
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const scale = FONT_SIZE / font.unitsPerEm

// Build one combined path, advancing x by each glyph's width + letter-spacing.
const combined = new opentype.Path()
let x = 0
for (const ch of TEXT) {
  const glyph = font.charToGlyph(ch)
  const gp = glyph.getPath(x, 0, FONT_SIZE) // baseline at y = 0
  combined.extend(gp)
  x += glyph.advanceWidth * scale + LETTER_SPACING
}

const bb = combined.getBoundingBox()
const vbX = bb.x1 - PAD
const vbY = bb.y1 - PAD
const vbW = bb.x2 - bb.x1 + PAD * 2
const vbH = bb.y2 - bb.y1 + PAD * 2

const d = combined.toPathData(2)

const component = `// AUTO-GENERATED by scripts/extract-outline.mjs — do not edit by hand.
// Exact Ms Madi outline of "Chorus" at 210px, 0.01em tracking.
export const CHORUS_VIEWBOX = '${vbX.toFixed(2)} ${vbY.toFixed(2)} ${vbW.toFixed(2)} ${vbH.toFixed(2)}'
export const CHORUS_WIDTH = ${vbW.toFixed(2)}
export const CHORUS_HEIGHT = ${vbH.toFixed(2)}
export const CHORUS_PATH = '${d}'
`

writeFileSync(join(__dirname, '..', 'src', 'chorusOutline.js'), component)
console.log('viewBox:', CHORUS_VIEWBOX_LOG())
function CHORUS_VIEWBOX_LOG() {
  return `${vbX.toFixed(2)} ${vbY.toFixed(2)} ${vbW.toFixed(2)} ${vbH.toFixed(2)}`
}
console.log('width x height:', vbW.toFixed(2), 'x', vbH.toFixed(2))
console.log('path length:', d.length, 'chars')
console.log('-> wrote src/chorusOutline.js')
